// Clue suggestions (SPEC §2.8): user's own published clues → curated crossword clues → dictionary clues.
// The data files may not exist yet (they are generated by `npm run wordlist`); missing files are simply empty.

import { normalizeAnswer, normalizeClue } from '../../site/shared/puzzle.js';
import { api, fetchStatic } from './api.js';

export const SOURCE_LABELS = {
  theme: 'Theme',
  user: 'Yours',
  curated: 'Curated',
  dictionary: 'Dictionary',
};

function asBank(value) {
  return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
}

class ClueBank extends EventTarget {
  banks = { user: {}, curated: {}, dictionary: {} };
  loaded = false;
  missing = [];
  #loading = null;

  /** Load all banks once (call again with force=true to refresh the user's clues after publishing). */
  load(force = false) {
    if (this.loaded && !force) return Promise.resolve(this);
    if (this.#loading) return this.#loading;
    this.#loading = (async () => {
      const missing = [];
      const opt = (p, name) => p.then((v) => { if (v === null) missing.push(name); return asBank(v); })
        .catch((err) => { console.warn(`Clue bank ${name} failed to load`, err); missing.push(name); return {}; });
      const [user, curated, dictionary] = await Promise.all([
        api.getUserClues().then(asBank).catch(() => ({})),
        opt(fetchStatic('data/clues-curated.json', 'json'), 'curated'),
        opt(fetchStatic('data/clues-dictionary.json', 'json'), 'dictionary'),
      ]);
      this.banks = { user, curated, dictionary };
      this.missing = missing;
      this.loaded = true;
      this.dispatchEvent(new Event('loaded'));
      return this;
    })().finally(() => { this.#loading = null; });
    return this.#loading;
  }

  /**
   * Suggestions for an answer, best first: [{ clue, source }]. Clues that contain the answer are dropped and
   * duplicates (case-insensitive) are removed. `themeClue` (from the theme list) comes first when given.
   */
  suggestions(answer, { themeClue = '', limit = 30 } = {}) {
    const word = normalizeAnswer(answer);
    if (!word) return [];
    const out = [];
    const seen = new Set();
    const push = (clue, source) => {
      const text = normalizeClue(clue);
      if (!text) return;
      const key = text.toLowerCase();
      if (seen.has(key)) return;
      if (word.length >= 3 && normalizeAnswer(text).includes(word)) return;
      seen.add(key);
      out.push({ clue: text, source });
    };
    if (themeClue) push(themeClue, 'theme');
    for (const source of ['user', 'curated', 'dictionary']) {
      const list = this.banks[source][word];
      if (Array.isArray(list)) for (const c of list) push(c, source);
    }
    return out.slice(0, limit);
  }
}

export const clueBank = new ClueBank();
